# Generated by Django 2.2.1 on 2019-06-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190606_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_business',
        ),
        migrations.DeleteModel(
            name='blog_health',
        ),
        migrations.DeleteModel(
            name='blog_style',
        ),
    ]
