# Generated by Django 2.2.1 on 2019-06-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190606_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_world',
        ),
    ]
